# Generated by Django 5.1.1 on 2024-11-23 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0071_alter_siteconfig_shop_type_alter_siteconfig_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', null=True)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('shop', models.ForeignKey(help_text='Select the shop to which this customer belongs.', on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', null=True)),
                ('reference_id', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('short_url', models.CharField(max_length=100)),
                ('provider', models.SmallIntegerField(choices=[(1, 'INR')], default=1)),
                ('currency', models.SmallIntegerField(choices=[(1, 'INR')], default=1)),
                ('amount', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('status_str', models.CharField(max_length=20)),
                ('request_json', models.JSONField()),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(help_text='Select the shop to which this payment belongs.', on_delete=django.db.models.deletion.CASCADE, to='payment.customer')),
                ('product', models.ForeignKey(blank=True, help_text='Select the shop to which this payment belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('shop', models.ForeignKey(help_text='Select the shop to which this payment belongs.', on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
