# Generated by Django 5.1.1 on 2024-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_customer_city_customer_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
