# Generated by Django 6.0.5 on 2026-05-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_background_img',
            name='image2',
            field=models.ImageField(default='default', upload_to='home_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home_background_img',
            name='image3',
            field=models.ImageField(default='default', upload_to='home_image'),
            preserve_default=False,
        ),
    ]
