# Generated by Django 6.0.5 on 2026-05-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
