# Generated by Django 6.0.5 on 2026-05-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('old', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='product')),
                ('stars', models.CharField(max_length=10)),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField()),
                ('badge', models.CharField(blank=True, max_length=20, null=True)),
                ('badgeLabel', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
