# Generated by Django 6.0.5 on 2026-05-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about')),
            ],
        ),
    ]
