# Generated by Django 6.0.5 on 2026-05-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_about_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=200)),
            ],
        ),
    ]
