# Generated by Django 6.0.5 on 2026-06-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_client_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
