# Generated by Django 6.0.5 on 2026-06-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
