# Generated by Django 6.0.5 on 2026-06-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='badgeLabel',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='review',
        ),
    ]
