# Generated by Django 6.0.5 on 2026-06-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='term_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
