# Generated by Django 6.0.5 on 2026-06-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_term_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term_conditions',
            old_name='update_at',
            new_name='last_update',
        ),
    ]
