# Generated by Django 6.0.5 on 2026-07-01 08:18

import django.db.models.deletion
from django.db import migrations, models


def backfill_order_numbers(apps, schema_editor):
    Order = apps.get_model('main', 'Order')
    for order in Order.objects.all():
        if not order.order_number:
            created = order.create_at.strftime('%Y%m%d') if order.create_at else '00000000'
            order.order_number = f"DC-{created}-{order.id:05d}"
        if order.payment_id:
            order.payment_method = 'Razorpay'
        order.save(update_fields=['order_number', 'payment_method'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_update_at_term_conditions_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash On Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='product_list',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product_list',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product_list',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='product_list',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product_list')),
            ],
        ),
        migrations.RunPython(backfill_order_numbers, migrations.RunPython.noop),
    ]
